---
# dummy secrets.yaml for CI
wifi_ssid: "ssid"
wifi_password: "password"
api_password: password
api_encryption_key: UwNeykeNiB00x6McK3xcI/Bh1IEm03lguAB0U4ScrTo=
ota_password: password
influxdb_host: host.example.org
influxdb_port: "8086"
influxdb_database: database
influxdb_user: user
influxdb_password: password
influxdb_scheme: http
slack_webhook_url_esphome_doorbell: https://example.org/dummy/url
