---

substitutions:
  myname: 501-sensor-ambient
  location: "501"

esphome:
  name: ${myname}

esp8266:
  board: esp01_1m

logger:
  level: debug

api:
  password: !secret api_password
debug:
  update_interval: 5s

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO0
  scl: GPIO2
  scan: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address ${myname}
    ssid:
      name: ESP Connected SSID ${myname}
    bssid:
      name: ESP Connected BSSID ${myname}
    mac_address:
      name: ESP Mac Wifi Address ${myname}
    scan_results:
      name: ESP Latest Scan Results ${myname}

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor ${myname}"
    update_interval: 60s

  - platform: uptime
    name: Uptime Sensor ${myname}

  - platform: htu21d
    temperature:
      name: "Temperature ${location}"
      id: temperature
    humidity:
      name: "Humidity ${location}"
      id: humidity
    update_interval: 60s

#font:
#  - file: /usr/local/share/fonts/Droid/DroidSans.ttf
#    id: font1
#    size: 24
#display:
#  - platform: ssd1306_i2c
#    model: "SSD1306 128x64"
#    address: 0x3C
#    lambda: |-
#      it.printf(127, 0, id(font1), TextAlign::TOP_RIGHT,
#        "%.2f°", id(temperature).state);
#      it.printf(127, 24, id(font1), TextAlign::TOP_RIGHT,
#        "%.1f%%", id(humidity).state);
