---

substitutions:
  myname: backgarden-doorbell-1
  location: "backgarden"

esphome:
  name: ${myname}
  on_boot:
    # post a message to slack upon boot. with priority higher than 200, the
    # network is available.
    priority: 200
    then:
      - http_request.post:
          url: !secret slack_webhook_url_esphome_doorbell
          # TLS verification does not work on ESP8266
          verify_ssl: false
          headers:
            Content-Type: application/json
          json:
            text: !lambda |-
              snprintf(id(buf), sizeof(id(buf)), "@here Someone pushed me at %s", "${location}");
              return id(buf);
            # enable group mention, makes `@here` work
            link_names: "true"

esp8266:
  board: nodemcuv2

logger:
  level: debug

api:
  password: !secret api_password

debug:
  update_interval: 5s

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: buf
    type: char[512]
    restore_value: no
    initial_value: ""

http_request:
  useragent: esphome/${myname}
  timeout: 10s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address ${myname}
    ssid:
      name: ESP Connected SSID ${myname}
    bssid:
      name: ESP Connected BSSID ${myname}
    mac_address:
      name: ESP Mac Wifi Address ${myname}
    scan_results:
      name: ESP Latest Scan Results ${myname}

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor ${myname}"
    update_interval: 60s

  - platform: uptime
    name: Uptime Sensor ${myname}

deep_sleep:
  run_duration: 10s
  # sleep indefinitely. the max value of sleep_duration on ESP8266 is about 3
  # hours 46 minutes. a value bigger than this makes ESP8266 in deep sleep
  # indefinitely.
  sleep_duration: 4h
