---

substitutions:
  myname: backgarden-switch-light-1
  location: "backgarden"

esphome:
  name: ${myname}

esp8266:
  board: esp8285

logger:
  level: debug

api:
  password: !secret api_password

debug:
  update_interval: 5s

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: buf
    type: char[512]
    restore_value: no
    initial_value: ""

http_request:
  useragent: esphome/${myname}
  timeout: 10s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address ${myname}
    ssid:
      name: ESP Connected SSID ${myname}
    bssid:
      name: ESP Connected BSSID ${myname}
    mac_address:
      name: ESP Mac Wifi Address ${myname}
    scan_results:
      name: ESP Latest Scan Results ${myname}

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor ${myname}"
    update_interval: 60s

  - platform: uptime
    name: Uptime Sensor ${myname}

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button ${myname}"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Relay ${myname}"
    pin: GPIO12
    # XXX do not keep state in EEPROM.
    # * the state does not change often
    # * when it is always on, you may turn on or off the device with an
    # external switch if present.
    restore_mode: ALWAYS_ON
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

web_server:
