---

substitutions:
  myname: lobby-clock-1
  location: lobby

esphome:
  name: ${myname}

esp8266:
  board: nodemcuv2

logger:
  level: debug

api:
  password: !secret api_password

debug:
  update_interval: 5s

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor ${myname}"
    update_interval: 60s
  - platform: uptime
    name: Uptime Sensor ${myname}

time:
  - platform: sntp
    id: sntp_time

display:
  platform: tm1637
  clk_pin: D6
  dio_pin: D5
  length: 4
  update_interval: 500ms
  intensity: 5
  lambda: |-
    static int i = 0;
    i++;
    if ((i % 2) == 0) {
      it.strftime("%H.%M", id(sntp_time).now());
    } else {
      it.strftime("%H%M", id(sntp_time).now());
    }
