---
name: Run tox tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Cache tox environment
        uses: actions/cache@v3
        with:
          path: .tox/python
          key: ${{ runner.os }}-tox-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: Cache ~/.platformio packages
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/config/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Test with tox
        run: tox

      - name: Copy dummy secrets.yaml for CI
        run: |
          cp config/.secrets.yaml config/secrets.yaml

      - name: Build all YAML configuration files
        # XXX tox does not allow to use backticks in command in tox.ini. as a
        # workaround, run `compile` here.
        run: |
          source .tox/python/bin/activate
          for F in `ls -1 config/*.yml`; do
            esphome compile "${F}"
          done
