---
name: Run tox tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Cache tox environment
        uses: actions/cache@v3
        with:
          path: .tox/python
          key: ${{ runner.os }}-tox-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-tox-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Test with tox
        run: tox

      - name: Build all YAML configuration files
        run: |
          source .tox/python/bin/activate
          for F in `ls -1 config/*.yml`; do
            esphome compile "${I}"
          done
