---

name: markdownlint

on:
  push:
  pull_request:

jobs:
  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main
        with:
          filesToIgnoreRegex: "(node_modules|.tox)\\/.*"
